version: "3.0"
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  query-app:
    build: ./query-app/
    environment:
      BROKER: mqtt
      TOPIC: control
      PORT: 1883
