version: "3.0"
services:
  broker:
    image: eclipse-mosquitto 
    ports:
      - 1883:1883
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  master:
    image: 10.1.2.121:5000/unique-master
    build: ./node-master
    environment:
      - TOPICPUB=upb/file/result
      - TOPICSUB=upb/file/search
      - HOST=research.upb.edu
      - PORT=21212
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    depends_on:
      - broker
  javasl:
    image: 10.1.2.121:5000/java-image
    build: ./java-slave
    environment:
      SERVER: master
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    depends_on:
      - broker
      - master
      - registry
  rubysl:
    image: 10.1.2.121:5000/ruby-image
    build: ./ruby-slave
    environment:
      SERVER: master
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    depends_on:
      - broker
      - master
      - registry
  mycsslave:
    ports:
      - 5006:80
      - 50052:443
    image: 10.1.2.121:5000/csharp-image
    build:
      context: ./MyCSSlave
      dockerfile: Dockerfile
    environment:
      SERVER: master
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    depends_on:
      - broker
      - master
      - registry
  registry:
    image: registry:2
    ports:
      - 5000:5000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:  
        constraints: [node.role == manager]


    
        
