version: "3.0"
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  node_pub_1:
    build: .
    environment:
      BROKER: mqtt
      TOPIC: control
      PORT: 1883
