version: '3.4'

services:
  mycsslave:
    ports:
      - 5006:80
      - 50052:443
    image: 10.1.2.121:5000/csharp-image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER: master
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

