version: "3.0"
services:
  broker:
    container_name: broker
    image: eclipse-mosquitto 
    ports:
      - 1883:1883
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mis-libros-net
  publisher1:
    container_name: pub1
    build: 
      context: ./
      dockerfile: Dockerfile
    networks:
      - mis-libros-net
networks:
  mis-libros-net:
    driver: bridge
