# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: general.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("general.proto", :syntax => :proto3) do
    add_message "generalInfoPackage.Empty" do
    end
    add_message "generalInfoPackage.RegistryInfo" do
      optional :ipAddress, :string, 1
      optional :name, :string, 2
    end
    add_message "generalInfoPackage.FileInfo" do
      optional :fileName, :string, 1
      optional :size, :uint32, 2
      optional :SlaveId, :string, 3
    end
    add_message "generalInfoPackage.FileName" do
      optional :fileName, :string, 1
    end
    add_message "generalInfoPackage.FileInfoList" do
      repeated :fileInfoList, :message, 1, "generalInfoPackage.FileInfo"
    end
  end
end

module GeneralInfoPackage
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generalInfoPackage.Empty").msgclass
  RegistryInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generalInfoPackage.RegistryInfo").msgclass
  FileInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generalInfoPackage.FileInfo").msgclass
  FileName = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generalInfoPackage.FileName").msgclass
  FileInfoList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generalInfoPackage.FileInfoList").msgclass
end
